"""init

Revision ID: e3b89e57a82e
Revises: 37149d3fa6a5
Create Date: 2022-10-21 12:04:17.972653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e3b89e57a82e'
down_revision = '37149d3fa6a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodedatabase',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('father_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('mother_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_family_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('information', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['userdatabase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['father_id'], ['nodedatabase.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['nodedatabase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userdatabase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('partnersmapper',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('husband_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('wife_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('wedding_date', sa.Date(), nullable=True),
    sa.Column('divorce_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['husband_id'], ['nodedatabase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wife_id'], ['nodedatabase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernodemapper',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('node_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodedatabase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['userdatabase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernodemapper')
    op.drop_table('partnersmapper')
    op.drop_table('nodedatabase')
    # ### end Alembic commands ###
